version: '2.4'

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - NODE_ENV=development
      target: build
    command: npm run dev
    ports:
      - '3030:3000/tcp'
      - '9229:9229/tcp'
    volumes:
      - .:/opt:delegated
    environment:
      - MONGO_URI
      - CLIENT_ID
      - CLIENT_SECRET
      - PUBLIC_URL
      - VATSIM_AUTH_URL
      - VACC_AUTH_URL
      - VACC_AUTH_TOKEN
      - VACC_LOGO_URL
      - VACC_IMPRINT_URL
      - JWT_SECRET
      - ALLOW_SIM=true
      - ALLOW_OBS_MASTER=true
      - LOG_LEVEL_CONSOLE=debug
      - LOG_LEVEL_FILE=none
      - FRONTEND_PROXY=http://frontend:5173/
  frontend:
    image: node:18-alpine
    working_dir: /app
    command: npm run spa-dev
    volumes:
      - .:/app:delegated
