version: '2.4'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - NODE_ENV=development
      target: build
    command: npm run dev
    ports:
      - '3030:3000/tcp'
      - '9229:9229/tcp'
    volumes:
      - .:/opt:delegated
    environment:
      - MONGO_URI
      - CLIENT_ID
      - CLIENT_SECRET
      - PUBLIC_URL
      - VATSIM_AUTH_URL
      - VACC_AUTH_URL
      - VACC_AUTH_TOKEN
      - VACC_LOGO_URL
      - VACC_IMPRINT_URL
      - JWT_SECRET
      - ALLOW_SIM=true
      - ALLOW_OBS_MASTER=true
  worker:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - NODE_ENV=development
      target: build
    command: npm run dev
    ports:
      - '9230:9229/tcp'
    volumes:
      - .:/opt:delegated
    environment:
      - MONGO_URI
      - ROLE=WORKER
